### PR TITLE
Low level survey

### PR DESCRIPTION
**Pull request by inorton**
I've added a low altitude survey type (sublclass of AerialContract)

The diff in here looks a lot worse than it is because I removed the mixed tabs from these files (sorry about that) I wish github did side-by-side diffs

### CODE REVIEW

**Comment by qsantos** [comment]
You can use the -w option from git-diff as a GET parameter. Here is the diff ignoring whitespaces:

https://github.com/Arsonide/FinePrint/pull/7/files?w=1

**Comment by inorton** [comment]
How about I do a separate pull request where I de-tabify all the source ?

**Comment by qsantos** [comment]
You can update the pull request by pushing to the branch inorton:low-level-survey. That way, you can either push a commit fixing what you want, or even rebase (for a clean history) and force a push (git push -f).

**Comment by inorton** [comment]
I'm happy with the code, I was only wishing I'd spotted the mixed tabs
before hand to make the diff seem simpler incrementally.

**Comment by Arsonide** [comment]
Hey inorton, I really appreciate the help, but I have been in the middle of some major refactoring. I was not updating the master except for major releases, but I recently set up a develop branch that will be more frequently updated. If you could resubmit this against that branch, I will see to incorporating it.

**Comment by inorton** [comment]
Hey that's fine, no prob. I'll try your dev branch :)

**Pull request closed without merging**
